<?php

namespace App\Repositories\User;
use App\models\User;
use App\Repositories\BaseRepository;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;


class UserRepository extends BaseRepository implements UserRepositoryInterface
{
    public function __construct(User $model)
    {
       parent::__construct($model);
    }

    public function getModel(): User
     {
        return parent::getModel();

     }

    public function query(array $payload = []): Builder
    {
        return parent::query($payload)->when(isset($payload['password'])); // TODO: Change the autogenerated stub
    }


}

